// Acceptance cases for every language the app ships agent instructions for
// (src/llm/instructions/agent-instructions.<code>.mts): da de en es fr it ko nl
// no pl ru sv.
//
// Each language gets a home whose zone and device names are in that language,
// because that is what users name them in Homey. `calls: []` means the fast
// path must NOT act (the turn goes to the LLM).
//
// Categories: positive | parallel | missing (target not stated) | negation |
// question (state query -> LLM) | irrelevant | invalid (out of bounds).
//
// Every language has the same 17 cases in the same order, so per-language
// numbers compare directly.

const call = (name, args) => ({ name, arguments: args });

export const LANGUAGES = {
    en: {
        home: {
            lightZones: ['Living room', 'Kitchen', 'Bedroom', 'Study', 'Garden'],
            thermostatZones: ['Living room', 'Bedroom', 'Bathroom'],
            blindZones: ['Living room', 'Bedroom'],
            switches: ['Christmas tree', 'Coffee machine', 'Dehumidifier'],
        },
        cases: [
            { q: 'turn on the kitchen lights', calls: [call('control_lights', { zone: 'Kitchen', action: 'on' })], cat: 'positive' },
            { q: 'switch off the lights in the bedroom', calls: [call('control_lights', { zone: 'Bedroom', action: 'off' })], cat: 'positive' },
            { q: 'dim the living room to 30 percent', calls: [call('control_lights', { zone: 'Living room', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'turn on the christmas tree', calls: [call('switch_device', { device: 'Christmas tree', action: 'on' })], cat: 'positive' },
            { q: 'set the bathroom to 22 degrees', calls: [call('set_thermostat', { zone: 'Bathroom', temperature: 22 })], cat: 'positive' },
            { q: 'close the blinds in the bedroom', calls: [call('control_blinds', { zone: 'Bedroom', action: 'close' })], cat: 'positive' },
            { q: 'set a timer for 10 minutes', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'add milk and eggs to the shopping list', calls: [call('add_to_shopping_list', { items: ['milk', 'eggs'] })], cat: 'positive' },
            { q: 'next song', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'turn off the garden lights and start the coffee machine', calls: [call('control_lights', { zone: 'Garden', action: 'off' }), call('switch_device', { device: 'Coffee machine', action: 'on' })], cat: 'parallel' },
            { q: 'turn on the lights', calls: [], cat: 'missing' },
            { q: 'set the thermostat to 21', calls: [], cat: 'missing' },
            { q: "don't turn off the study lights", calls: [], cat: 'negation' },
            { q: 'are the kitchen lights on?', calls: [], cat: 'question' },
            { q: 'what will the weather be tomorrow', calls: [], cat: 'irrelevant' },
            { q: 'play some jazz in the living room', calls: [], cat: 'irrelevant' },
            { q: 'set the bedroom to 45 degrees', calls: [], cat: 'invalid' },
        ],
    },
    nl: {
        home: {
            lightZones: ['Woonkamer', 'Keuken', 'Slaapkamer', 'Werkkamer', 'Tuin'],
            thermostatZones: ['Woonkamer', 'Slaapkamer', 'Badkamer'],
            blindZones: ['Woonkamer', 'Slaapkamer'],
            switches: ['Kerstboom', 'Koffiezetapparaat', 'Luchtontvochtiger'],
        },
        cases: [
            { q: 'doe het licht in de keuken aan', calls: [call('control_lights', { zone: 'Keuken', action: 'on' })], cat: 'positive' },
            { q: 'zet de lampen in de slaapkamer uit', calls: [call('control_lights', { zone: 'Slaapkamer', action: 'off' })], cat: 'positive' },
            { q: 'dim de woonkamer naar 30 procent', calls: [call('control_lights', { zone: 'Woonkamer', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'zet de kerstboom aan', calls: [call('switch_device', { device: 'Kerstboom', action: 'on' })], cat: 'positive' },
            { q: 'zet de badkamer op 22 graden', calls: [call('set_thermostat', { zone: 'Badkamer', temperature: 22 })], cat: 'positive' },
            { q: 'doe de gordijnen in de slaapkamer dicht', calls: [call('control_blinds', { zone: 'Slaapkamer', action: 'close' })], cat: 'positive' },
            { q: 'zet een timer van 10 minuten', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'zet melk en eieren op het boodschappenlijstje', calls: [call('add_to_shopping_list', { items: ['melk', 'eieren'] })], cat: 'positive' },
            { q: 'volgend nummer', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'doe het licht in de tuin uit en zet het koffiezetapparaat aan', calls: [call('control_lights', { zone: 'Tuin', action: 'off' }), call('switch_device', { device: 'Koffiezetapparaat', action: 'on' })], cat: 'parallel' },
            { q: 'doe het licht aan', calls: [], cat: 'missing' },
            { q: 'zet de thermostaat op 21', calls: [], cat: 'missing' },
            { q: 'doe het licht in de werkkamer niet uit', calls: [], cat: 'negation' },
            { q: 'is het licht in de keuken aan?', calls: [], cat: 'question' },
            { q: 'wat voor weer wordt het morgen', calls: [], cat: 'irrelevant' },
            { q: 'speel wat jazz in de woonkamer', calls: [], cat: 'irrelevant' },
            { q: 'zet de slaapkamer op 45 graden', calls: [], cat: 'invalid' },
        ],
    },
    no: {
        home: {
            lightZones: ['Stue', 'Kjøkken', 'Soverom', 'Kontor', 'Hage'],
            thermostatZones: ['Stue', 'Soverom', 'Bad'],
            blindZones: ['Stue', 'Soverom'],
            switches: ['Juletre', 'Kaffetrakter', 'Avfukter'],
        },
        cases: [
            { q: 'skru på lyset på kjøkkenet', calls: [call('control_lights', { zone: 'Kjøkken', action: 'on' })], cat: 'positive' },
            { q: 'slå av lyset på soverommet', calls: [call('control_lights', { zone: 'Soverom', action: 'off' })], cat: 'positive' },
            { q: 'demp lyset i stua til 30 prosent', calls: [call('control_lights', { zone: 'Stue', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'slå på juletreet', calls: [call('switch_device', { device: 'Juletre', action: 'on' })], cat: 'positive' },
            { q: 'sett badet til 22 grader', calls: [call('set_thermostat', { zone: 'Bad', temperature: 22 })], cat: 'positive' },
            { q: 'lukk persiennene på soverommet', calls: [call('control_blinds', { zone: 'Soverom', action: 'close' })], cat: 'positive' },
            { q: 'sett en timer på 10 minutter', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'legg til melk og egg på handlelisten', calls: [call('add_to_shopping_list', { items: ['melk', 'egg'] })], cat: 'positive' },
            { q: 'neste sang', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'slå av lyset i hagen og slå på kaffetrakteren', calls: [call('control_lights', { zone: 'Hage', action: 'off' }), call('switch_device', { device: 'Kaffetrakter', action: 'on' })], cat: 'parallel' },
            { q: 'slå på lyset', calls: [], cat: 'missing' },
            { q: 'sett termostaten til 21', calls: [], cat: 'missing' },
            { q: 'ikke slå av lyset på kontoret', calls: [], cat: 'negation' },
            { q: 'er lyset på kjøkkenet på?', calls: [], cat: 'question' },
            { q: 'hvordan blir været i morgen', calls: [], cat: 'irrelevant' },
            { q: 'spill litt jazz i stua', calls: [], cat: 'irrelevant' },
            { q: 'sett soverommet til 45 grader', calls: [], cat: 'invalid' },
        ],
    },
    da: {
        home: {
            lightZones: ['Stue', 'Køkken', 'Soveværelse', 'Kontor', 'Have'],
            thermostatZones: ['Stue', 'Soveværelse', 'Badeværelse'],
            blindZones: ['Stue', 'Soveværelse'],
            switches: ['Juletræ', 'Kaffemaskine', 'Affugter'],
        },
        cases: [
            { q: 'tænd lyset i køkkenet', calls: [call('control_lights', { zone: 'Køkken', action: 'on' })], cat: 'positive' },
            { q: 'sluk lyset i soveværelset', calls: [call('control_lights', { zone: 'Soveværelse', action: 'off' })], cat: 'positive' },
            { q: 'dæmp lyset i stuen til 30 procent', calls: [call('control_lights', { zone: 'Stue', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'tænd juletræet', calls: [call('switch_device', { device: 'Juletræ', action: 'on' })], cat: 'positive' },
            { q: 'sæt badeværelset til 22 grader', calls: [call('set_thermostat', { zone: 'Badeværelse', temperature: 22 })], cat: 'positive' },
            { q: 'luk persiennerne i soveværelset', calls: [call('control_blinds', { zone: 'Soveværelse', action: 'close' })], cat: 'positive' },
            { q: 'sæt en timer på 10 minutter', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'tilføj mælk og æg til indkøbslisten', calls: [call('add_to_shopping_list', { items: ['mælk', 'æg'] })], cat: 'positive' },
            { q: 'næste sang', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'sluk lyset i haven og tænd kaffemaskinen', calls: [call('control_lights', { zone: 'Have', action: 'off' }), call('switch_device', { device: 'Kaffemaskine', action: 'on' })], cat: 'parallel' },
            { q: 'tænd lyset', calls: [], cat: 'missing' },
            { q: 'sæt termostaten til 21', calls: [], cat: 'missing' },
            { q: 'sluk ikke lyset på kontoret', calls: [], cat: 'negation' },
            { q: 'er lyset i køkkenet tændt?', calls: [], cat: 'question' },
            { q: 'hvordan bliver vejret i morgen', calls: [], cat: 'irrelevant' },
            { q: 'spil noget jazz i stuen', calls: [], cat: 'irrelevant' },
            { q: 'sæt soveværelset til 45 grader', calls: [], cat: 'invalid' },
        ],
    },
    de: {
        home: {
            lightZones: ['Wohnzimmer', 'Küche', 'Schlafzimmer', 'Arbeitszimmer', 'Garten'],
            thermostatZones: ['Wohnzimmer', 'Schlafzimmer', 'Badezimmer'],
            blindZones: ['Wohnzimmer', 'Schlafzimmer'],
            switches: ['Weihnachtsbaum', 'Kaffeemaschine', 'Luftentfeuchter'],
        },
        cases: [
            { q: 'mach das Licht in der Küche an', calls: [call('control_lights', { zone: 'Küche', action: 'on' })], cat: 'positive' },
            { q: 'schalte das Licht im Schlafzimmer aus', calls: [call('control_lights', { zone: 'Schlafzimmer', action: 'off' })], cat: 'positive' },
            { q: 'dimme das Wohnzimmer auf 30 Prozent', calls: [call('control_lights', { zone: 'Wohnzimmer', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'schalte den Weihnachtsbaum ein', calls: [call('switch_device', { device: 'Weihnachtsbaum', action: 'on' })], cat: 'positive' },
            { q: 'stelle das Badezimmer auf 22 Grad', calls: [call('set_thermostat', { zone: 'Badezimmer', temperature: 22 })], cat: 'positive' },
            { q: 'schließe die Jalousien im Schlafzimmer', calls: [call('control_blinds', { zone: 'Schlafzimmer', action: 'close' })], cat: 'positive' },
            { q: 'stell einen Timer auf 10 Minuten', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'setze Milch und Eier auf die Einkaufsliste', calls: [call('add_to_shopping_list', { items: ['Milch', 'Eier'] })], cat: 'positive' },
            { q: 'nächstes Lied', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'mach das Licht im Garten aus und schalte die Kaffeemaschine ein', calls: [call('control_lights', { zone: 'Garten', action: 'off' }), call('switch_device', { device: 'Kaffeemaschine', action: 'on' })], cat: 'parallel' },
            { q: 'mach das Licht an', calls: [], cat: 'missing' },
            { q: 'stell die Heizung auf 21', calls: [], cat: 'missing' },
            { q: 'schalte das Licht im Arbeitszimmer nicht aus', calls: [], cat: 'negation' },
            { q: 'ist das Licht in der Küche an?', calls: [], cat: 'question' },
            { q: 'wie wird das Wetter morgen', calls: [], cat: 'irrelevant' },
            { q: 'spiel etwas Jazz im Wohnzimmer', calls: [], cat: 'irrelevant' },
            { q: 'stelle das Schlafzimmer auf 45 Grad', calls: [], cat: 'invalid' },
        ],
    },
    es: {
        home: {
            lightZones: ['Salón', 'Cocina', 'Dormitorio', 'Despacho', 'Jardín'],
            thermostatZones: ['Salón', 'Dormitorio', 'Baño'],
            blindZones: ['Salón', 'Dormitorio'],
            switches: ['Árbol de Navidad', 'Cafetera', 'Deshumidificador'],
        },
        cases: [
            { q: 'enciende la luz de la cocina', calls: [call('control_lights', { zone: 'Cocina', action: 'on' })], cat: 'positive' },
            { q: 'apaga las luces del dormitorio', calls: [call('control_lights', { zone: 'Dormitorio', action: 'off' })], cat: 'positive' },
            { q: 'atenúa el salón al 30 por ciento', calls: [call('control_lights', { zone: 'Salón', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'enciende el árbol de Navidad', calls: [call('switch_device', { device: 'Árbol de Navidad', action: 'on' })], cat: 'positive' },
            { q: 'pon el baño a 22 grados', calls: [call('set_thermostat', { zone: 'Baño', temperature: 22 })], cat: 'positive' },
            { q: 'cierra las persianas del dormitorio', calls: [call('control_blinds', { zone: 'Dormitorio', action: 'close' })], cat: 'positive' },
            { q: 'pon un temporizador de 10 minutos', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'añade leche y huevos a la lista de la compra', calls: [call('add_to_shopping_list', { items: ['leche', 'huevos'] })], cat: 'positive' },
            { q: 'siguiente canción', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'apaga la luz del jardín y enciende la cafetera', calls: [call('control_lights', { zone: 'Jardín', action: 'off' }), call('switch_device', { device: 'Cafetera', action: 'on' })], cat: 'parallel' },
            { q: 'enciende la luz', calls: [], cat: 'missing' },
            { q: 'pon el termostato a 21', calls: [], cat: 'missing' },
            { q: 'no apagues la luz del despacho', calls: [], cat: 'negation' },
            { q: '¿está encendida la luz de la cocina?', calls: [], cat: 'question' },
            { q: 'dime el tiempo de mañana', calls: [], cat: 'irrelevant' },
            { q: 'pon algo de jazz en el salón', calls: [], cat: 'irrelevant' },
            { q: 'pon el dormitorio a 45 grados', calls: [], cat: 'invalid' },
        ],
    },
    fr: {
        home: {
            lightZones: ['Salon', 'Cuisine', 'Chambre', 'Bureau', 'Jardin'],
            thermostatZones: ['Salon', 'Chambre', 'Salle de bain'],
            blindZones: ['Salon', 'Chambre'],
            switches: ['Sapin de Noël', 'Cafetière', 'Déshumidificateur'],
        },
        cases: [
            { q: 'allume la lumière de la cuisine', calls: [call('control_lights', { zone: 'Cuisine', action: 'on' })], cat: 'positive' },
            { q: 'éteins la lumière dans la chambre', calls: [call('control_lights', { zone: 'Chambre', action: 'off' })], cat: 'positive' },
            { q: 'baisse le salon à 30 pour cent', calls: [call('control_lights', { zone: 'Salon', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'allume le sapin de Noël', calls: [call('switch_device', { device: 'Sapin de Noël', action: 'on' })], cat: 'positive' },
            { q: 'mets la salle de bain à 22 degrés', calls: [call('set_thermostat', { zone: 'Salle de bain', temperature: 22 })], cat: 'positive' },
            { q: 'ferme les volets de la chambre', calls: [call('control_blinds', { zone: 'Chambre', action: 'close' })], cat: 'positive' },
            { q: 'mets un minuteur de 10 minutes', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'ajoute du lait et des œufs à la liste de courses', calls: [call('add_to_shopping_list', { items: ['lait', 'œufs'] })], cat: 'positive' },
            { q: 'chanson suivante', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'éteins la lumière du jardin et allume la cafetière', calls: [call('control_lights', { zone: 'Jardin', action: 'off' }), call('switch_device', { device: 'Cafetière', action: 'on' })], cat: 'parallel' },
            { q: 'allume la lumière', calls: [], cat: 'missing' },
            { q: 'mets le thermostat à 21', calls: [], cat: 'missing' },
            { q: "n'éteins pas la lumière du bureau", calls: [], cat: 'negation' },
            { q: 'est-ce que la lumière de la cuisine est allumée ?', calls: [], cat: 'question' },
            { q: 'quel temps fera-t-il demain', calls: [], cat: 'irrelevant' },
            { q: 'mets du jazz dans le salon', calls: [], cat: 'irrelevant' },
            { q: 'mets la chambre à 45 degrés', calls: [], cat: 'invalid' },
        ],
    },
    it: {
        home: {
            lightZones: ['Soggiorno', 'Cucina', 'Camera da letto', 'Studio', 'Giardino'],
            thermostatZones: ['Soggiorno', 'Camera da letto', 'Bagno'],
            blindZones: ['Soggiorno', 'Camera da letto'],
            switches: ['Albero di Natale', 'Macchina del caffè', 'Deumidificatore'],
        },
        cases: [
            { q: 'accendi la luce in cucina', calls: [call('control_lights', { zone: 'Cucina', action: 'on' })], cat: 'positive' },
            { q: 'spegni le luci in camera da letto', calls: [call('control_lights', { zone: 'Camera da letto', action: 'off' })], cat: 'positive' },
            { q: 'abbassa il soggiorno al 30 per cento', calls: [call('control_lights', { zone: 'Soggiorno', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: "accendi l'albero di Natale", calls: [call('switch_device', { device: 'Albero di Natale', action: 'on' })], cat: 'positive' },
            { q: 'imposta il bagno a 22 gradi', calls: [call('set_thermostat', { zone: 'Bagno', temperature: 22 })], cat: 'positive' },
            { q: 'chiudi le tapparelle in camera da letto', calls: [call('control_blinds', { zone: 'Camera da letto', action: 'close' })], cat: 'positive' },
            { q: 'imposta un timer di 10 minuti', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'aggiungi latte e uova alla lista della spesa', calls: [call('add_to_shopping_list', { items: ['latte', 'uova'] })], cat: 'positive' },
            { q: 'prossima canzone', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'spegni la luce in giardino e accendi la macchina del caffè', calls: [call('control_lights', { zone: 'Giardino', action: 'off' }), call('switch_device', { device: 'Macchina del caffè', action: 'on' })], cat: 'parallel' },
            { q: 'accendi la luce', calls: [], cat: 'missing' },
            { q: 'imposta il termostato a 21', calls: [], cat: 'missing' },
            { q: 'non spegnere la luce nello studio', calls: [], cat: 'negation' },
            { q: 'la luce in cucina è accesa?', calls: [], cat: 'question' },
            { q: 'che tempo farà domani', calls: [], cat: 'irrelevant' },
            { q: "metti un po' di jazz in soggiorno", calls: [], cat: 'irrelevant' },
            { q: 'imposta la camera da letto a 45 gradi', calls: [], cat: 'invalid' },
        ],
    },
    ko: {
        home: {
            lightZones: ['거실', '주방', '침실', '서재', '정원'],
            thermostatZones: ['거실', '침실', '욕실'],
            blindZones: ['거실', '침실'],
            switches: ['크리스마스 트리', '커피머신', '제습기'],
        },
        cases: [
            { q: '주방 불 켜줘', calls: [call('control_lights', { zone: '주방', action: 'on' })], cat: 'positive' },
            { q: '침실 불 꺼줘', calls: [call('control_lights', { zone: '침실', action: 'off' })], cat: 'positive' },
            { q: '거실 조명 30 퍼센트로 낮춰줘', calls: [call('control_lights', { zone: '거실', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: '크리스마스 트리 켜줘', calls: [call('switch_device', { device: '크리스마스 트리', action: 'on' })], cat: 'positive' },
            { q: '욕실 22도로 맞춰줘', calls: [call('set_thermostat', { zone: '욕실', temperature: 22 })], cat: 'positive' },
            { q: '침실 블라인드 닫아줘', calls: [call('control_blinds', { zone: '침실', action: 'close' })], cat: 'positive' },
            { q: '10분 타이머 맞춰줘', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: '장보기 목록에 우유랑 계란 추가해줘', calls: [call('add_to_shopping_list', { items: ['우유', '계란'] })], cat: 'positive' },
            { q: '다음 곡', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: '정원 불 끄고 커피머신 켜줘', calls: [call('control_lights', { zone: '정원', action: 'off' }), call('switch_device', { device: '커피머신', action: 'on' })], cat: 'parallel' },
            { q: '불 켜줘', calls: [], cat: 'missing' },
            { q: '온도 21도로 맞춰줘', calls: [], cat: 'missing' },
            { q: '서재 불 끄지 마', calls: [], cat: 'negation' },
            { q: '주방 불 켜져 있어?', calls: [], cat: 'question' },
            { q: '내일 날씨 어때', calls: [], cat: 'irrelevant' },
            { q: '거실에서 재즈 틀어줘', calls: [], cat: 'irrelevant' },
            { q: '침실 45도로 맞춰줘', calls: [], cat: 'invalid' },
        ],
    },
    pl: {
        home: {
            lightZones: ['Salon', 'Kuchnia', 'Sypialnia', 'Gabinet', 'Ogród'],
            thermostatZones: ['Salon', 'Sypialnia', 'Łazienka'],
            blindZones: ['Salon', 'Sypialnia'],
            switches: ['Choinka', 'Ekspres do kawy', 'Osuszacz'],
        },
        cases: [
            { q: 'włącz światło w kuchni', calls: [call('control_lights', { zone: 'Kuchnia', action: 'on' })], cat: 'positive' },
            { q: 'zgaś światło w sypialni', calls: [call('control_lights', { zone: 'Sypialnia', action: 'off' })], cat: 'positive' },
            { q: 'przyciemnij salon do 30 procent', calls: [call('control_lights', { zone: 'Salon', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'włącz choinkę', calls: [call('switch_device', { device: 'Choinka', action: 'on' })], cat: 'positive' },
            { q: 'ustaw łazienkę na 22 stopnie', calls: [call('set_thermostat', { zone: 'Łazienka', temperature: 22 })], cat: 'positive' },
            { q: 'zamknij rolety w sypialni', calls: [call('control_blinds', { zone: 'Sypialnia', action: 'close' })], cat: 'positive' },
            { q: 'ustaw minutnik na 10 minut', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'dodaj mleko i jajka do listy zakupów', calls: [call('add_to_shopping_list', { items: ['mleko', 'jajka'] })], cat: 'positive' },
            { q: 'następna piosenka', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'zgaś światło w ogrodzie i włącz ekspres do kawy', calls: [call('control_lights', { zone: 'Ogród', action: 'off' }), call('switch_device', { device: 'Ekspres do kawy', action: 'on' })], cat: 'parallel' },
            { q: 'włącz światło', calls: [], cat: 'missing' },
            { q: 'ustaw termostat na 21', calls: [], cat: 'missing' },
            { q: 'nie gaś światła w gabinecie', calls: [], cat: 'negation' },
            { q: 'czy światło w kuchni jest włączone?', calls: [], cat: 'question' },
            { q: 'jaka będzie jutro pogoda', calls: [], cat: 'irrelevant' },
            { q: 'włącz trochę jazzu w salonie', calls: [], cat: 'irrelevant' },
            { q: 'ustaw sypialnię na 45 stopni', calls: [], cat: 'invalid' },
        ],
    },
    ru: {
        home: {
            lightZones: ['Гостиная', 'Кухня', 'Спальня', 'Кабинет', 'Сад'],
            thermostatZones: ['Гостиная', 'Спальня', 'Ванная'],
            blindZones: ['Гостиная', 'Спальня'],
            switches: ['Ёлка', 'Кофеварка', 'Осушитель'],
        },
        cases: [
            { q: 'включи свет на кухне', calls: [call('control_lights', { zone: 'Кухня', action: 'on' })], cat: 'positive' },
            { q: 'выключи свет в спальне', calls: [call('control_lights', { zone: 'Спальня', action: 'off' })], cat: 'positive' },
            { q: 'приглуши свет в гостиной до 30 процентов', calls: [call('control_lights', { zone: 'Гостиная', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'включи ёлку', calls: [call('switch_device', { device: 'Ёлка', action: 'on' })], cat: 'positive' },
            { q: 'установи в ванной 22 градуса', calls: [call('set_thermostat', { zone: 'Ванная', temperature: 22 })], cat: 'positive' },
            { q: 'закрой жалюзи в спальне', calls: [call('control_blinds', { zone: 'Спальня', action: 'close' })], cat: 'positive' },
            { q: 'поставь таймер на 10 минут', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'добавь молоко и яйца в список покупок', calls: [call('add_to_shopping_list', { items: ['молоко', 'яйца'] })], cat: 'positive' },
            { q: 'следующая песня', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'выключи свет в саду и включи кофеварку', calls: [call('control_lights', { zone: 'Сад', action: 'off' }), call('switch_device', { device: 'Кофеварка', action: 'on' })], cat: 'parallel' },
            { q: 'включи свет', calls: [], cat: 'missing' },
            { q: 'поставь термостат на 21', calls: [], cat: 'missing' },
            { q: 'не выключай свет в кабинете', calls: [], cat: 'negation' },
            { q: 'свет на кухне включён?', calls: [], cat: 'question' },
            { q: 'какая завтра погода', calls: [], cat: 'irrelevant' },
            { q: 'включи джаз в гостиной', calls: [], cat: 'irrelevant' },
            { q: 'установи в спальне 45 градусов', calls: [], cat: 'invalid' },
        ],
    },
    sv: {
        home: {
            lightZones: ['Vardagsrum', 'Kök', 'Sovrum', 'Arbetsrum', 'Trädgård'],
            thermostatZones: ['Vardagsrum', 'Sovrum', 'Badrum'],
            blindZones: ['Vardagsrum', 'Sovrum'],
            switches: ['Julgran', 'Kaffebryggare', 'Avfuktare'],
        },
        cases: [
            { q: 'tänd ljuset i köket', calls: [call('control_lights', { zone: 'Kök', action: 'on' })], cat: 'positive' },
            { q: 'släck ljuset i sovrummet', calls: [call('control_lights', { zone: 'Sovrum', action: 'off' })], cat: 'positive' },
            { q: 'dimma vardagsrummet till 30 procent', calls: [call('control_lights', { zone: 'Vardagsrum', action: 'dim', brightness_percent: 30 })], cat: 'positive' },
            { q: 'sätt på julgranen', calls: [call('switch_device', { device: 'Julgran', action: 'on' })], cat: 'positive' },
            { q: 'ställ badrummet på 22 grader', calls: [call('set_thermostat', { zone: 'Badrum', temperature: 22 })], cat: 'positive' },
            { q: 'stäng persiennerna i sovrummet', calls: [call('control_blinds', { zone: 'Sovrum', action: 'close' })], cat: 'positive' },
            { q: 'sätt en timer på 10 minuter', calls: [call('set_timer', { minutes: 10 })], cat: 'positive' },
            { q: 'lägg till mjölk och ägg på inköpslistan', calls: [call('add_to_shopping_list', { items: ['mjölk', 'ägg'] })], cat: 'positive' },
            { q: 'nästa låt', calls: [call('control_music', { action: 'next' })], cat: 'positive' },
            { q: 'släck ljuset i trädgården och sätt på kaffebryggaren', calls: [call('control_lights', { zone: 'Trädgård', action: 'off' }), call('switch_device', { device: 'Kaffebryggare', action: 'on' })], cat: 'parallel' },
            { q: 'tänd ljuset', calls: [], cat: 'missing' },
            { q: 'ställ termostaten på 21', calls: [], cat: 'missing' },
            { q: 'släck inte ljuset i arbetsrummet', calls: [], cat: 'negation' },
            { q: 'är ljuset i köket tänt?', calls: [], cat: 'question' },
            { q: 'hur blir vädret imorgon', calls: [], cat: 'irrelevant' },
            { q: 'spela lite jazz i vardagsrummet', calls: [], cat: 'irrelevant' },
            { q: 'ställ sovrummet på 45 grader', calls: [], cat: 'invalid' },
        ],
    },
};
